# Generated by Django 5.1.2 on 2025-07-07 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='oauth_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='oauth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('apple', 'Apple')], default='email', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(condition=models.Q(('oauth_provider', 'email'), ('oauth_id__isnull', False), _connector='OR'), name='oauth_id_required_for_oauth_providers'),
        ),
    ]
